"""Render data/ideas_matrix.json to IDEAS_MATRIX.md: every idea, its pros and cons, and a verdict."""
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).parent
DATA = json.loads((ROOT / "data" / "ideas_matrix.json").read_text(encoding="utf-8"))
LABEL = dict(winner="**WINNER**", adopt="adopt", test="test", fallback="fallback", niche="niche", killed="~~killed~~")

WINNER_DESIGN = """## The winner design, in one breath
Malvern clay extruded into **cellular units with staggered webs** (graded skin, husk-pored core, dense
ground bed faces), fired in a **husk-gasifier kiln**, dry-stacked into **rod-clamped panels** and tilted up
into a **16–20-sided round plan** locked by **wedged key blocks**, capped by a **post-tensioned ribbed dome**
under **cocciopesto and fired scale tiles**, wearing **hung interlocking siding** and standing on **fluted
drainage boots**. Inside: **bio-lime block partitions** between treated bamboo posts. First product: the
**round drum storm shelter**. Larger homes are **clusters of domes**. Made in a **small Malvern factory**
that ships kits by truckload. Layer-by-layer detail and sources: `SYNTHESIS.md`."""


def render():
    ideas = DATA["ideas"]
    counts = Counter(i["verdict"] for i in ideas)
    out = [
        "# IDEAS MATRIX — every idea explored, with pros, cons and a verdict",
        "### generated by `ideas_matrix.py` from `data/ideas_matrix.json` — edit the JSON, then re-run",
        "",
        "> " + DATA["_about"].split(". Rendered")[0] + ".",
        "> Verdicts: **WINNER** = in the lead design · adopt = a supporting part of the kit · test = promising,"
        " waiting on a measurement · fallback = proven backup · niche = only for certain sites or uses ·"
        " ~~killed~~ = failed its numbers (the reasons are in `GRAVEYARD.md`).",
        "",
        "**" + " · ".join(f"{counts[v]} {v}" for v in DATA["verdicts"]) + f"** — {len(ideas)} ideas in all.",
        "",
        WINNER_DESIGN,
        "",
    ]
    cats = list(dict.fromkeys(i["cat"] for i in ideas))
    for cat in cats:
        out += [f"## {cat}", "", "| idea | pros | cons | verdict | evidence |", "|---|---|---|---|---|"]
        rows = sorted((i for i in ideas if i["cat"] == cat), key=lambda i: DATA["verdicts"].index(i["verdict"]))
        for i in rows:
            name = f"**{i['idea']}**" if i["verdict"] == "winner" else i["idea"]
            out.append(f"| {name} | {i['pros']} | {i['cons']} | {LABEL[i['verdict']]} | `{i['where']}` |")
        out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    text = render()
    (ROOT / "IDEAS_MATRIX.md").write_text(text, encoding="utf-8")
    print(f"wrote IDEAS_MATRIX.md: {len(DATA['ideas'])} ideas")
